### PR TITLE
Custom checkboxes done

### PR DESCRIPTION
**Pull request by minnaseppala**

### CODE REVIEW

**Comment by vanchau** [comment]
How about 

.status-filter-item-name {
  user-select: none;
  position: relative;
  **bottom: 2px;**
  margin-left: 6px;
}

:)

**Comment by minnaseppala** [comment]
> How about
> 
> .status-filter-item-name {
> user-select: none;
> position: relative;
> **bottom: 2px;**
> margin-left: 6px;
> }
> 
> :)

lifted the titles up by one pixel, thanks for noticing the horrible oversight

**Comment by vanchau** [comment]
Should the cursor change into a finger when clickable

**Comment by minnaseppala** [comment]
> Should the cursor change into a finger when clickable

good point, made the changes

**Pull request merged**
