### PR TITLE
Update TrashBinDetails.js

### PR DESCRIPTION
**Pull request by PatBom**
added buttons to switch view between all events and opened events in trashbin details

### CODE REVIEW

**Comment by PatBom** [comment]
-will clean variables and other dirty code, edits
-render switch does bring additional value since it gives more information to user by telling the type of event rather than having only the trigger code numbers.
-bin emptied button not implemented, cannot get data on empty events yet
-colors & design are subject to change

**Comment by vanchau** [comment]
My point considering the renderSwitch wasn't to show trigger codes/event type but rather not showing anything at all, as only opened/emptied should be enough? Also, if we have 2 buttons (opened/emptied), shouldn't All button show only these two?

Emptied button: not sure what the convention is but seems odd to push stuff to master that isn't working yet. At least by showing an empty list it could indicate that the button works as there is no emptied events

**Comment by PatBom** [comment]
Ok in your vision only processed events would be shown by all tab. That makes sense too. I still like the idea of being able to view the raw unprocessed events coming from the TouchTag (as they contain pretty useful info like has the tag been deactivated suddenly) so I moved those events under their own tab that isn't "All events".

Now we have tabs for All processed events, Open, Closed events + raw events(for now atleast). I made the event log collapsable to save some space on the site. Might not want to show a long list of events 100% of the time, especially should the site get graphs, maps /other widgets.

Cleaned the code quite a bit, replaced all remaining indentations made with spacebar with indentations made with tab; mixing the two made for uneven whitespace when viewing the code on different readers, code was also a pain to edit when space and tab is used randomly throughout the code so no more of that mess.

Fixed other errors and warnings, commented parts of the code.

**Comment by PatBom** [comment]
log filters

**Pull request merged**
